name: rl-an-intro
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - gymnasium
  - imageio
  - imageio-ffmpeg
  - opencv
  - pandas
  - python=3.11
  - pillow
  - matplotlib
  - numpy
  - pip
  - tqdm
  - pip:
    - gymnasium[toy-text]
