name: rl-an-intro
channels:
  - defaults
  - conda-forge
dependencies:
  - dynaconf
  - gymnasium-all
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pillow
  - python=3.11
  - pytorch
  - tensorboard
  - tqdm
