default:
  envs: []
reinforce:
  envs:
    - 
      # https://gymnasium.farama.org/environments/box2d/lunar_lander/
      # "An episode is considered a solution if it scores at least 200 points."
      env_spec_id: "LunarLander-v2"
      inner_dims: 256
      num_episodes: 6000
      lr: .0003
      gamma: 1
      max_lookahead: 100
      num_videos: 20
    - 
      # https://gymnasium.farama.org/environments/classic_control/cart_pole/
      # "The threshold for rewards is 500 for v1"
      env_spec_id: "CartPole-v1"
      inner_dims: 512
      num_episodes: 2000
      lr: .0003
      gamma: 1
      max_lookahead: 100
      num_videos: 20
    -
      # https://gymnasium.farama.org/environments/classic_control/acrobot/
      # "The reward threshold is -100"
      env_spec_id: 'Acrobot-v1'
      inner_dims: 128
      num_episodes: 1000
      lr: .0003
      gamma: 1
      max_lookahead: 100
      num_videos: 20
